# 01: Probability Distribution

In [47]:
import tensorflow_probability as tfp

In [48]:
tfd = tfp.distributions

We can use a variety of distributions listed at: https://www.tensorflow.org/probability/api_docs/python/tfp/distributions

## Example distribution: Normal Distribution

In [69]:
d_normal = tfd.Normal(loc=[5], scale=2)

For Normal distribution, `loc` indicates $\mu$ and `scale` indicates $\sigma$.

Let's see some interesting methods belong to this distribution.

### `cdf`

`cdf(x) := P[X <= x]`

In [50]:
d_normal.cdf(5)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.5], dtype=float32)>

In [51]:
d_normal.cdf(5 + 2 * 2)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.97724986], dtype=float32)>

### `cross_entropy`

`H[P, Q] = E_p[-log q(X)] = -int_F p(x) log q(x) dr(x)`

In [52]:
q = tfd.Normal(loc=[100], scale=2)

In [53]:
d_normal.cross_entropy(q)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1130.237], dtype=float32)>

In [54]:
d_normal.cross_entropy(d_normal)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.1120858], dtype=float32)>

We can see that cross-entropy is large when a wrong probability distribution is assumed. In this case, `d_noraml` is the desired probability distribution (ground truth), and `q` can be thought of a wrong estimation of the distribution.

### `sample`

Generate samples of the specified shape.

In [55]:
d_normal.sample(5)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[7.7086496],
       [5.793973 ],
       [5.9988112],
       [5.350604 ],
       [5.849042 ]], dtype=float32)>

In [56]:
q.sample(5)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 97.0292 ],
       [100.31859],
       [ 98.20633],
       [103.60803],
       [ 98.87997]], dtype=float32)>

### `prob`

Probability density/mass function

In [62]:
d_normal.prob(d_normal.sample(5))

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.17189574],
       [0.12691882],
       [0.1952384 ],
       [0.19133274],
       [0.18537201]], dtype=float32)>

In [64]:
d_normal.prob(20)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2171607e-13], dtype=float32)>

### `mean` & `stddev`

In [65]:
d_normal.mean()

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.], dtype=float32)>

In [66]:
d_normal.stddev()

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>

In [67]:
q.mean()

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([100.], dtype=float32)>

In [68]:
q.stddev()

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>